---
- name: Add OS vars
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}.yml"

- name: Check if installed
  ansible.builtin.shell: |
    {{ package_manager }} list --installed | grep keybase
  register: keybase_installed
  changed_when: false
  ignore_errors: true

- name: Install keybase on Fedora
  ansible.builtin.dnf:
    name: "https://prerelease.keybase.io/keybase_amd64.rpm"
    state: present
    disable_gpg_check: true
  when:
    - keybase_installed.rc != 0
    - ansible_distribution == "Fedora"

- name: Install keybase on Ubuntu
  ansible.builtin.apt:
    deb: "https://prerelease.keybase.io/keybase_amd64.deb"
    state: present
  when:
    - keybase_installed.rc != 0
    - ansible_distribution == "Ubuntu"

- name: Run keybase
  ansible.builtin.command: run_keybase
  args:
    creates: /keybase

# https://github.com/keybase/client/issues/24688
- name: Fix keybase on newer Fedoras
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/user/keybase.gui.service
    regexp: '^ExecStart=/opt/keybase/Keybase'
    line: "ExecStart=/opt/keybase/Keybase --disable-seccomp-filter-sandbox"
