username: michab

krew_plugins:
  - sniff
  - hns
  - ctx
  - ns

pip_apps:
  - name: pip
    virtualenv_enabled: false
  - name: pyOpenSSL
    virtualenv_enabled: false
  - name: ansible
    virtualenv_enabled: false
  - name: argcomplete
    virtualenv_enabled: false
  - name: azure-cli
    virtualenv_enabled: true
  - name: ansible-lint
    virtualenv_enabled: false
  - name: yamllint
    virtualenv_enabled: false
  - name: psutil
    virtualenv_enabled: false
  - name: pywinrm
    virtualenv_enabled: false
  - name: niet
    virtualenv_enabled: true
