---
- name: Install PIP virtualenv
  ansible.builtin.pip:
    name: "virtualenv"
    state: present

- name: Install PIP Apps globally
  ansible.builtin.pip:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ pip_apps }}"
  when: not item.virtualenv_enabled

- name: Install PIP Apps in virtualenv
  ansible.builtin.pip:
    name: "{{ item.name }}"
    state: present
    virtualenv: "{{ virtualenv_install_path }}/{{ item.name }}"
  with_items:
    - "{{ pip_apps }}"
  when: item.virtualenv_enabled

- name: Create a symbolic link
  ansible.builtin.file:
    src: "{{ virtualenv_install_path }}/{{ item.name }}/bin/{{ item.name }}"
    dest: "/usr/local/bin/{{ item.name }}"
    owner: root
    group: root
    state: link
  with_items:
    - "{{ pip_apps }}"
  when: item.virtualenv_enabled and not item.name == "azure-cli"

- name: Create a symbolic link for azure-cli
  ansible.builtin.file:
    src: "{{ virtualenv_install_path }}/{{ item.name }}/bin/az"
    dest: "/usr/local/bin/az"
    owner: root
    group: root
    state: link
  with_items:
    - "{{ pip_apps }}"
  when: item.virtualenv_enabled and item.name == "azure-cli"

- name: Import update tasks.
  ansible.builtin.import_tasks: update.yml
  tags:
    - update
