---
- name: Update global PIP Apps
  ansible.builtin.pip:
    name: "{{ item.name }}"
    state: latest  # noqa package-latest
  with_items:
    - "{{ pip_apps }}"
  when: not item.virtualenv_enabled
  tags:
    - update

- name: Update virtualenv PIP apps
  ansible.builtin.pip:
    name: "{{ item.name }}"
    state: latest  # noqa package-latest
    virtualenv: "{{ virtualenv_install_path }}/{{ item.name }}"
  when: item.virtualenv_enabled
  with_items:
    - "{{ pip_apps }}"
  tags:
    - update
