---
- name: Get installed version of ctop
  ansible.builtin.shell: |
    set -o pipefail && ctop -v | cut -d' ' -f3 | cut -d',' -f1
  register: installed_ctop_version
  changed_when: false
  ignore_errors: true
  args:
    executable: /usr/bin/bash

- name: Installed version of ctop
  ansible.builtin.debug:
    var: installed_ctop_version.stdout

- name: Get latest version of ctop
  ansible.builtin.include_tasks: get_latest_version.yml
  when: ctop_version is not defined

- name: Install ctop
  ansible.builtin.include_tasks: install.yml
  when: installed_ctop_version.stdout != ctop_version
