---
- name: Directory for k9s   # noqa risky-file-permissions
  ansible.builtin.file:
    path: /tmp/k9s
    state: directory

- name: Download k9s binary   # noqa risky-file-permissions
  ansible.builtin.get_url:
    url: "https://github.com/derailed/k9s/releases/download/v{{ k9s_version }}/k9s_Linux_amd64.tar.gz"
    dest: /tmp/k9s/k9s.tar.gz
    mode: "0644"

- name: Unarchive a file that is already on the remote machine
  become: true
  ansible.builtin.unarchive:
    src: /tmp/k9s/k9s.tar.gz
    dest: "{{ applications_install_path }}"
    remote_src: true
    exclude:
      - README.md
      - LICENCE

- name: Delete content & directory
  ansible.builtin.file:
    state: absent
    path: /tmp/k9s
