---
- name: Get installed version of aws-cli
  become: true
  become_user: "{{ username }}"
  ansible.builtin.shell: set -o pipefail && aws --version | cut -d "/" -f2 | awk '{print $1}'
  register: installed_aws_cli_version
  changed_when: false
  ignore_errors: true
  args:
    executable: /usr/bin/bash

- name: "Installed version of aws-cli:"
  ansible.builtin.debug:
    var: installed_aws_cli_version.stdout

- name: Tasks
  ansible.builtin.include_tasks: get_latest_version.yml
  when: aws_cli_version is not defined

- name: Tasks
  ansible.builtin.include_tasks: install.yml
  when: installed_aws_cli_version.stdout != aws_cli_version
