---
- name: Get installed version
  ansible.builtin.shell: packer version | head -n 1 | grep v | cut -d'v' -f2
  register: installed_packer_version
  changed_when: false
  ignore_errors: true

- name: Installed version of packer
  ansible.builtin.debug:
    var: installed_packer_version.stdout

- name: Tasks
  ansible.builtin.include_tasks: get_latest_version.yml
  when: packer_version is not defined

- name: Download packer  # noqa risky-file-permissions
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip"
    dest: /tmp/packer.zip
  when: installed_packer_version.stdout != packer_version

- name: Unarchive a file that is already on the remote machine
  become: true
  ansible.builtin.unarchive:
    src: /tmp/packer.zip
    dest: "{{ applications_install_path }}/"
    remote_src: true
  when: installed_packer_version.stdout != packer_version

- name: Set permissions packer
  become: true
  ansible.builtin.file:
    path: "{{ applications_install_path }}/packer"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Delete packer archive
  ansible.builtin.file:
    state: absent
    path: /tmp/packer.zip
