---
- name: Get installed version of hadolint
  become: true
  become_user: "{{ username }}"
  ansible.builtin.shell: |
    set -o pipefail && hadolint -v | awk '{print $4}' | cut -d'-' -f1 | cut -d'v' -f2
  register: installed_hadolint_version
  changed_when: false
  ignore_errors: true
  args:
    executable: /usr/bin/bash

- name: "Installed version of hadolint:"
  ansible.builtin.debug:
    var: installed_hadolint_version.stdout

- name: Tasks
  ansible.builtin.include_tasks: get_latest_version.yml
  when: hadolint_version is not defined

- name: Tasks
  ansible.builtin.include_tasks: install.yml
  when: installed_hadolint_version.stdout != hadolint_version
