---
- name: Directory for kail   # noqa risky-file-permissions
  ansible.builtin.file:
    path: /tmp/kail
    state: directory

- name: Download kail binary   # noqa risky-file-permissions
  ansible.builtin.get_url:
    url: "https://github.com/boz/kail/releases/download/v{{ kail_version }}/kail_v{{ kail_version }}_linux_amd64.tar.gz"
    dest: /tmp/kail/kail.tar.gz

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: /tmp/kail/kail.tar.gz
    dest: /tmp/kail
    remote_src: true

- name: Copy kail
  ansible.builtin.copy:
    src: "/tmp/kail/kail"
    dest: "/usr/local/bin/kail"
    remote_src: true
    mode: 0755
    owner: root
    group: root

- name: Delete content & directory
  ansible.builtin.file:
    state: absent
    path: /tmp/kail
