# ➜ kubectl plugin list
# The following compatible plugins are available:
# /home/mikee/.krew/bin/kubectl-krew
# /home/mikee/.krew/bin/kubectl-sniff
---
- name: Upgrade krew
  ansible.builtin.include_tasks: krew/update.yml
  when: krew_version is not defined

- name: Get installed version
  become: true
  become_user: "{{ username }}"
  ansible.builtin.shell: set -o pipefail ~/.krew/bin/kubectl-krew version | grep GitTag | awk '{print $2}' | cut -d'v' -f2
  register: installed_krew_version
  changed_when: false
  ignore_errors: true
  args:
    executable: /usr/bin/bash

- name: "Installed version of krew:"
  ansible.builtin.debug:
    var: installed_krew_version.stdout

- name: Tasks
  ansible.builtin.include_tasks: krew/get_latest_version.yml
  when: krew_version is not defined

- name: Tasks
  ansible.builtin.include_tasks: krew/install.yml
  when: installed_krew_version.stdout != krew_version

- name: Tasks
  ansible.builtin.import_tasks: krew/plugins.yml
