---
- name: Get installed version
  ansible.builtin.shell: set -o pipefail && kubectl version --short --client=true | grep -i client | cut -d'v' -f2
  register: installed_kubectl_version
  changed_when: false
  ignore_errors: true
  args:
    executable: /usr/bin/bash

- name: Installed version of kubectl
  ansible.builtin.debug:
    var: installed_kubectl_version.stdout

- name: Get latest version of kubectl
  ansible.builtin.include_tasks: get_latest_version.yml
  when: kubectl_version is not defined

- name: Download kubectl  # noqa risky-file-permissions
  become: true
  ansible.builtin.get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl"
    dest: "{{ applications_install_path }}/kubectl"
    force: true
  when: installed_kubectl_version.stdout != kubectl_version

- name: Set permissions kubectl
  become: true
  ansible.builtin.file:
    path: "{{ applications_install_path }}/kubectl"
    owner: root
    group: root
    mode: "0755"
