---
- name: Directory for stern  # noqa risky-file-permissions
  ansible.builtin.file:
    path: /tmp/stern
    state: directory

- name: Download stern  # noqa risky-file-permissions
  ansible.builtin.get_url:
    url: "https://github.com/stern/stern/releases/download/v{{ stern_version }}/stern_{{ stern_version }}_linux_amd64.tar.gz"
    dest: /tmp/stern/stern.tar.gz

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: /tmp/stern/stern.tar.gz
    dest: /tmp/stern
    remote_src: true

- name: Copy stern
  become: true
  ansible.builtin.copy:
    src: "/tmp/stern/stern"
    dest: "{{ applications_install_path }}/stern"
    owner: root
    group: root
    mode: "0755"
    remote_src: true

- name: Delete content & directory
  ansible.builtin.file:
    state: absent
    path: /tmp/stern
