---
- name: Check if argo command exist
  ansible.builtin.stat:
    path: /usr/local/bin/argo
  register: argo_binary

- name: Checking if binary exist, if not, will download it.
  when: not argo_binary.stat.exists
  block:
    - name: Get Argo binary
      ansible.builtin.get_url:
        url: "https://github.com/argoproj/argo-workflows/releases/download/v{{ argo_version }}/argo-linux-amd64.gz"
        dest: /tmp/argo-linux-amd64.gz
        mode: 0755
        owner: root
        group: root

    - name: Extract binary  # noqa no-changed-when
      ansible.builtin.command: |
        gunzip -f /tmp/argo-linux-amd64.gz
        mv /tmp/argo-linux-amd64 /usr/local/bin/argo
        chmod 755 /usr/local/bin/argo
      args:
        executable: /bin/bash
