---
- name: Get installed version
  ansible.builtin.shell: terraform version | head -n 1 | grep v | cut -d'v' -f2
  register: installed_terraform_version
  changed_when: false
  ignore_errors: true

- name: Installed version of terraform
  ansible.builtin.debug:
    var: installed_terraform_version.stdout

- name: Get latest version of terraform
  ansible.builtin.include_tasks: get_latest_version.yml
  when: terraform_version is not defined

- name: Download terraform  # noqa risky-file-permissions
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: /tmp/terraform.zip
  when: installed_terraform_version.stdout != terraform_version

- name: Unarchive a file that is already on the remote machine
  become: true
  ansible.builtin.unarchive:
    src: /tmp/terraform.zip
    dest: "{{ applications_install_path }}/"
    remote_src: true
  when: installed_terraform_version.stdout != terraform_version

- name: Set permissions terraform
  become: true
  ansible.builtin.file:
    path: "{{ applications_install_path }}/terraform"
    owner: root
    group: root
    mode: "0755"

- name: Delete terraform archive
  ansible.builtin.file:
    state: absent
    path: /tmp/terraform.zip
