---
- name: "ZSH autocomplete"  # noqa latest[git]
  become: true
  become_user: "{{ item }}"
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    update: true
  loop:
    - "{{ username }}"
    - root

- name: "ZSH Syntax Highlighting"  # noqa latest[git]
  become: true
  become_user: "{{ item }}"
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting'
    dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    update: true
  loop:
    - "{{ username }}"
    - root

- name: "Dracula theme"  # noqa latest[git]
  become: true
  become_user: "{{ item }}"
  ansible.builtin.git:
    repo: 'https://github.com/dracula/zsh.git'
    dest: "~/.oh-my-zsh/custom/themes/dracula"
    update: true
  loop:
    - "{{ username }}"
    - root

- name: "Oh-my-zsh config"
  become: true
  ansible.builtin.template:
    src: oh_my_zsh_zshrc.j2
    dest: "~{{ item }}/.zshrc"
    owner: "{{ item }}"
    backup: true
    mode: "0644"
  loop:
    - "{{ username }}"
    - root

# Fixing apt-get fzf package
- name: Download fzf key-bindings  # noqa risky-file-permissions
  become: true
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.zsh"
    dest: /usr/share/doc/fzf/examples/key-bindings.zsh
  when: ansible_distribution == "Ubuntu"
