---
- name: "Create directory for work profiles"  # noqa risky-file-permissions
  ansible.builtin.file:
    path: "~{{ username }}/.work_profiles"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: "Add zshrc for work profiles"
  ansible.builtin.copy:
    src: templates/work.zshrc.j2
    dest: "~{{ username }}/.work_profiles/.zshrc"
    owner: "{{ username }}"
    group: "{{ username }}"
    backup: true
    mode: 0644
