---
- name: Ubuntu WSL bootstrap
  hosts: local
  become: true
  roles:
    - apps/ctop
    - apps/oh_my_zsh
    - apps/terraform
    - apps/packer
    - apps/terragrunt
    - apps/dive

- name: Include a playbook for generic provision
  import_playbook: generic.yml
